/**
 * NOTE:
 * To denote Chapter Translation language,
 * translated fields such as Titles and Descriptions,
 * the API expects a 2-letter language code in accordance with the ISO 639-1 standard.
 *
 * Additionally, some cases require the 5-letter extension if the alpha-2 code is not sufficient
 * to determine the correct sub-type of a language,
 * in the style of `$language-$region`, e.g. zh-hk or pt-br.
 *
 * Because there is no standardized method of denoting romanized translations,
 * we chose to append the `-ro` suffix.
 * For example the romanized version of 五等分の花嫁
 * is 5Toubun no Hanayome or Gotoubun no Hanayome.
 *
 * Both would have the `ja-ro` language code,
 * alternative versions are inserted as alternative titles.
 * This is a clear distinction from
 * the localized en translation The Quintessential Quintuplets.
 */
export type DexLocalizedString = Partial<Record<DexLocales, string>>;

/**
 * MangaDex's extension of ISO6391 for romanized locales.
 */
export enum DexLocales {
	"Simplified Chinese" = "zh",
	"Traditional Chinese" = "zh-hk",
	"Brazilian Portugese" = "pt-br",
	"Castilian Spanish" = "es",
	"Latin American Spanish" = "es-la",
	"Romanized Japanese" = "ja-ro",
	"Romanized Korean" = "ko-ro",
	"Romanized Chinese" = "zh-ro",
	"Afar" = "aa",
	"Abkhaz" = "ab",
	"Avestan" = "ae",
	"Afrikaans" = "af",
	"Akan" = "ak",
	"Amharic" = "am",
	"Aragonese" = "an",
	"Arabic" = "ar",
	"Assamese" = "as",
	"Avaric" = "av",
	"Aymara" = "ay",
	"Azerbaijani" = "az",
	"Bashkir" = "ba",
	"Belarusian" = "be",
	"Bulgarian" = "bg",
	"Bislama" = "bi",
	"Bambara" = "bm",
	"Bengali" = "bn",
	"Tibetan" = "bo",
	"Breton" = "br",
	"Bosnian" = "bs",
	"Catalan" = "ca",
	"Chechen" = "ce",
	"Chamorro" = "ch",
	"Corsican" = "co",
	"Cree" = "cr",
	"Czech" = "cs",
	"Old_Church_Slavonic" = "cu",
	"Chuvash" = "cv",
	"Welsh" = "cy",
	"Danish" = "da",
	"German" = "de",
	"Divehi" = "dv",
	"Dzongkha" = "dz",
	"Ewe" = "ee",
	"Greek" = "el",
	"English" = "en",
	"Esperanto" = "eo",
	"Estonian" = "et",
	"Basque" = "eu",
	"Persian" = "fa",
	"Fula" = "ff",
	"Finnish" = "fi",
	"Fijian" = "fj",
	"Faroese" = "fo",
	"French" = "fr",
	"Western_Frisian" = "fy",
	"Irish" = "ga",
	"Scottish_Gaelic" = "gd",
	"Galician" = "gl",
	"Guaraní" = "gn",
	"Gujarati" = "gu",
	"Manx" = "gv",
	"Hausa" = "ha",
	"Hebrew" = "he",
	"Hindi" = "hi",
	"Hiri_Motu" = "ho",
	"Croatian" = "hr",
	"Haitian" = "ht",
	"Hungarian" = "hu",
	"Armenian" = "hy",
	"Herero" = "hz",
	"Interlingua" = "ia",
	"Indonesian" = "id",
	"Interlingue" = "ie",
	"Igbo" = "ig",
	"Nuosu" = "ii",
	"Inupiaq" = "ik",
	"Ido" = "io",
	"Icelandic" = "is",
	"Italian" = "it",
	"Inuktitut" = "iu",
	"Japanese" = "ja",
	"Javanese" = "jv",
	"Georgian" = "ka",
	"Kongo" = "kg",
	"Kikuyu" = "ki",
	"Kwanyama" = "kj",
	"Kazakh" = "kk",
	"Kalaallisut" = "kl",
	"Khmer" = "km",
	"Kannada" = "kn",
	"Korean" = "ko",
	"Kanuri" = "kr",
	"Kashmiri" = "ks",
	"Kurdish" = "ku",
	"Komi" = "kv",
	"Cornish" = "kw",
	"Kyrgyz" = "ky",
	"Latin" = "la",
	"Luxembourgish" = "lb",
	"Ganda" = "lg",
	"Limburgish" = "li",
	"Lingala" = "ln",
	"Lao" = "lo",
	"Lithuanian" = "lt",
	"Luba-Katanga" = "lu",
	"Latvian" = "lv",
	"Malagasy" = "mg",
	"Marshallese" = "mh",
	"Māori" = "mi",
	"Macedonian" = "mk",
	"Malayalam" = "ml",
	"Mongolian" = "mn",
	"Marathi" = "mr",
	"Malay" = "ms",
	"Maltese" = "mt",
	"Burmese" = "my",
	"Nauru" = "na",
	"Norwegian_Bokmål" = "nb",
	"Northern_Ndebele" = "nd",
	"Nepali" = "ne",
	"Ndonga" = "ng",
	"Dutch" = "nl",
	"Norwegian_Nynorsk" = "nn",
	"Norwegian" = "no",
	"Southern_Ndebele" = "nr",
	"Navajo" = "nv",
	"Chichewa" = "ny",
	"Occitan" = "oc",
	"Ojibwe" = "oj",
	"Oromo" = "om",
	"Oriya" = "or",
	"Ossetian" = "os",
	"Panjabi" = "pa",
	"Pāli" = "pi",
	"Polish" = "pl",
	"Pashto" = "ps",
	"Portuguese" = "pt",
	"Quechua" = "qu",
	"Romansh" = "rm",
	"Kirundi" = "rn",
	"Romanian" = "ro",
	"Russian" = "ru",
	"Kinyarwanda" = "rw",
	"Sanskrit" = "sa",
	"Sardinian" = "sc",
	"Sindhi" = "sd",
	"Northern_Sami" = "se",
	"Sango" = "sg",
	"Sinhala" = "si",
	"Slovak" = "sk",
	"Slovenian" = "sl",
	"Samoan" = "sm",
	"Shona" = "sn",
	"Somali" = "so",
	"Albanian" = "sq",
	"Serbian" = "sr",
	"Swati" = "ss",
	"Southern_Sotho" = "st",
	"Sundanese" = "su",
	"Swedish" = "sv",
	"Swahili" = "sw",
	"Tamil" = "ta",
	"Telugu" = "te",
	"Tajik" = "tg",
	"Thai" = "th",
	"Tigrinya" = "ti",
	"Turkmen" = "tk",
	"Tagalog" = "tl",
	"Tswana" = "tn",
	"Tonga" = "to",
	"Turkish" = "tr",
	"Tsonga" = "ts",
	"Tatar" = "tt",
	"Twi" = "tw",
	"Tahitian" = "ty",
	"Uyghur" = "ug",
	"Ukrainian" = "uk",
	"Urdu" = "ur",
	"Uzbek" = "uz",
	"Venda" = "ve",
	"Vietnamese" = "vi",
	"Volapük" = "vo",
	"Walloon" = "wa",
	"Wolof" = "wo",
	"Xhosa" = "xh",
	"Yiddish" = "yi",
	"Yoruba" = "yo",
	"Zhuang" = "za",
	"Zulu" = "zu",
}
